linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - gocognit
    - goconst
    - dupl

linters-settings:
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 15
  govet:
    enable-all: true
  dupl:
    threshold: 150
  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  exclude-use-default: false
