/**
 * Script to generate TypeScript types from JSON schemas.
 * Run with: npx tsx packages/metadata/scripts/generate-types.ts
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, basename } from 'node:path';

const SCHEMAS_DIR = join(import.meta.dirname, '../../../packages/schema/schemas');
const OUTPUT_DIR = join(import.meta.dirname, '../src/types');

const SCHEMA_FILES = [
  'author.schema.json',
  'abstract.schema.json',
  'frontmatter.schema.json',
];

const BANNER = `/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
 * and run generate-types to regenerate this file.
 */
`;

async function generateTypes(): Promise<void> {
  await mkdir(OUTPUT_DIR, { recursive: true });

  // Dynamic import to avoid loading json-schema-to-typescript at startup
  const { compile } = await import('json-schema-to-typescript');

  for (const schemaFile of SCHEMA_FILES) {
    const schemaPath = join(SCHEMAS_DIR, schemaFile);
    const typeName = basename(schemaFile, '.schema.json');
    const outputPath = join(OUTPUT_DIR, `${typeName}.ts`);

    const schema = JSON.parse(await readFile(schemaPath, 'utf-8'));

    const ts = await compile(schema, typeName, {
      bannerComment: BANNER,
      additionalProperties: false,
      style: {
        singleQuote: true,
        semi: true,
        trailingComma: 'none',
      },
    });

    await writeFile(outputPath, ts, 'utf-8');
    console.log(`Generated ${outputPath}`);
  }

  // Generate types/index.ts barrel file
  const barrel = SCHEMA_FILES
    .map((f) => {
      const name = basename(f, '.schema.json');
      return `export type * from './${name}.js';`;
    })
    .join('\n');

  await writeFile(join(OUTPUT_DIR, 'index.ts'), barrel + '\n', 'utf-8');
  console.log('Generated types/index.ts');
}

generateTypes().catch((err) => {
  console.error(err);
  process.exit(1);
});
