/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
 * and run generate-types to regenerate this file.
 */

/**
 * Schema for _author.yml — author information.
 */
export interface AuthorMetadata {
  /**
   * List of authors.
   */
  authors: AuthorObject[];
  [k: string]: unknown;
}
export interface AuthorObject {
  /**
   * Full name of the author.
   */
  name: string;
  /**
   * Contact email for the author.
   */
  email?: string;
  /**
   * Contact phone for the author.
   */
  phone?: string;
  /**
   * Contact fax for the author.
   */
  fax?: string;
  /**
   * URL for the author.
   */
  url?: string;
  /**
   * Academic titles or professional certifications.
   */
  degrees?: string[];
  /**
   * ORCID identifier (16 digits with hyphens, last digit may be X).
   */
  orcid?: string;
  /**
   * Notes to attach to the author.
   */
  note?: string;
  /**
   * Author's acknowledgements.
   */
  acknowledgements?: string;
  /**
   * Author's roles (CRediT contributor roles).
   */
  roles?: string[];
  /**
   * Whether this author is the corresponding author.
   */
  corresponding?: boolean;
  /**
   * Whether this author contributed equally.
   */
  'equal-contributor'?: boolean;
  /**
   * Whether this author is deceased.
   */
  deceased?: boolean;
  /**
   * Identifier for referencing this author in other fields.
   */
  id?: string;
  /**
   * Author affiliations.
   */
  affiliations?: AffiliationObject[];
  [k: string]: unknown;
}
export interface AffiliationObject {
  /**
   * Institution or organization name.
   */
  name: string;
  /**
   * Department within the affiliation.
   */
  department?: string;
  /**
   * Team or research group within the affiliation.
   */
  group?: string;
  /**
   * City of the affiliation.
   */
  city?: string;
  /**
   * Region of the affiliation.
   */
  region?: string;
  /**
   * State of the affiliation.
   */
  state?: string;
  /**
   * Country of the affiliation.
   */
  country?: string;
  /**
   * Postal code of the affiliation.
   */
  'postal-code'?: string;
  /**
   * URL of the affiliation.
   */
  url?: string;
  /**
   * 16-digit International Standard Name Identifier.
   */
  isni?: number;
  /**
   * 4-6 digit Ringgold ID.
   */
  ringgold?: number;
  /**
   * Research Organization Registry (ROR) ID.
   */
  ror?: string;
  /**
   * Identifier for referencing this affiliation.
   */
  id?: string;
  [k: string]: unknown;
}
