/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
 * and run generate-types to regenerate this file.
 */

/**
 * Schema for _frontmatter.yml — title, date, keywords, license, copyright, funding, citation, subject.
 */
export interface FrontmatterMetadata {
  /**
   * The article title.
   */
  title: string;
  /**
   * Publication or submission date.
   */
  date?: string;
  /**
   * Keywords for the article.
   */
  keywords?: string[];
  /**
   * License for the article (e.g. 'CC BY').
   */
  license?: string;
  /**
   * Copyright statement for the article.
   */
  copyright?: string;
  /**
   * Funding statement for the article.
   */
  funding?: string;
  /**
   * CSL citation metadata for the article itself.
   */
  citation?: {
    [k: string]: unknown;
  };
  /**
   * Subject classification using SKOS.
   */
  subject?: {
    /**
     * The subject text (skos:prefLabel).
     */
    text: string;
    /**
     * The SKOS concept scheme URI.
     */
    authority: string;
    /**
     * The concept identifier within the scheme.
     */
    term: string;
  };
  [k: string]: unknown;
}
